damontecres/StashAppAndroidTV

- README.md
- Users who are self-hosting docker containers often use things such as Kodi which are downloaded in this way.  This familiar program may already be installed and is certainly the most straightforward way to sideload an APK.
- Added a link to enable developer mode and unknown apps on FireSticks/FireCube/FireSticks, in addition to the existing AndroidTV links.
> Add clear instructions for downloader-style installers and FireOS

- app/src/main/java/com/github/damontecres/stashapp/PlaybackActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/PlaybackVideoFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
This is a quality-of-life improvement. When exiting a playing video, pass the current position back to the `VideoDetailsFragment`, so the user can optionally resume the playback.
This helps when seeking in a video if you accidentally press `back` too many times (trying to get rid of the controls), you can resume the video playback. This even seems to work despite #6.
The position is *not* persisted and is lost when the `VideoDetailsFragment` is removed (e.g. pressing back on the details page).
Some apps remember playback positions persistently, which might be a good future enhancement?
> Add (temporary) resume to video playback

- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
Since querying Stash for a empty list of performer IDs will actually return 25 "random" performers, the video details page should only query for performers if there are actually performers to query for.
Without this change, scenes without any performers set will list the "random" performers in the `VideoDetailsFragment` page.
> If scene has no performers, don't try to query for any

- README.md
Closes #10 
Recommend using the short URL https://aftv.news/745800 for installation
> Update install instructions with short url

- app/src/main/java/com/github/damontecres/stashapp/Constants.kt
- app/src/main/java/com/github/damontecres/stashapp/ErrorFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/PerformerFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/PerformerListActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/QueryEngine.kt
- app/src/main/java/com/github/damontecres/stashapp/StashSearchFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/StashPagingSource.kt
Queries (except for the connection test) are migrated to `QueryEngine` which incorporates extra error handling for network, HTTP, and syntax errors.
Additionally, activities that performer multiple queries use `async` to prevent propagating exceptions. This means on the main page, an error during the performers query won't crash the app nor prevent the scenes/studio queries from completing.
Errors are logged as toasts including the name for easier debugging.
This PR might help figure out what's happening in #12
> Add much better error handling

- app/build.gradle.kts
- app/src/main/graphql/Configuration.graphql
- app/src/main/graphql/FindSavedFilter.graphql
- app/src/main/java/com/github/damontecres/stashapp/Constants.kt
- app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/PerformerActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/PerformerListActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/QueryEngine.kt
- app/src/main/java/com/github/damontecres/stashapp/SceneListActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/StashGridFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/StudioActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/StudioListActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/TagActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/TagListActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/data/DataType.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/StashPagingSource.kt
- app/src/main/java/com/github/damontecres/stashapp/suppliers/PerformerDataSupplier.kt
- app/src/main/java/com/github/damontecres/stashapp/suppliers/SceneDataSupplier.kt
- app/src/main/java/com/github/damontecres/stashapp/suppliers/StudioDataSupplier.kt
- app/src/main/java/com/github/damontecres/stashapp/suppliers/TagDataSupplier.kt
Closes #17
This PR does two major things:
1. Use the UI configured on the Stash server for the main page
2. Use the default filters for supported data types on their respective list pages
This significantly aligns the app's UI with the web UI.
A significant amount of manual parsing is done for object filters since they do not have a graphql schema. I have not tested every single possible filter, but I suspect most (or all) will work just fine.
> Use rows & filters from server

- .gitmodules
Use a tagged release of `stashapp/stash` instead of the `develop` branch.
I generally want the Android TV to work with the latest released Stash version.
> Use a tag for the stash server submodule

- app/build.gradle.kts
- app/src/main/java/com/github/damontecres/stashapp/Constants.kt
- app/src/test/java/com/github/damontecres/stashapp/ObjectFilterParsingTests.kt
- app/src/test/resources/performer_savedfilter.json
- app/src/test/resources/scene_savedfilter.json
Follow up to #22
Adds some basic unit tests for parsing saved filters for scenes & performers by adding a filter for every available attribute.
These tests uncovered some bugs in the parsing code which are now fixed.
> Fix parsing saved filters

- app/src/main/java/com/github/damontecres/stashapp/PlaybackVideoFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/data/Scene.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/ScenePresenter.kt
Fixes some bugs:
1. Show the duration for non-direct streamed scenes thus allowing easier seeking
2. Corrects the aspect ratio for the thumbnail on video details (though it's still kinda small)
3. Prevents duplicate performers/tags from being added on video details
> A few bug fixes

- app/src/main/AndroidManifest.xml
- app/src/main/graphql/FindMovies.graphql
- app/src/main/java/com/github/damontecres/stashapp/Comparators.kt
- app/src/main/java/com/github/damontecres/stashapp/Constants.kt
- app/src/main/java/com/github/damontecres/stashapp/FilterListActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/MainTitleView.kt
- app/src/main/java/com/github/damontecres/stashapp/MovieActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/MovieFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/MovieListActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/QueryEngine.kt
- app/src/main/java/com/github/damontecres/stashapp/StashItemViewClickListener.kt
- app/src/main/java/com/github/damontecres/stashapp/StashSearchFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/data/DataType.kt
- app/src/main/java/com/github/damontecres/stashapp/data/Movie.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/MoviePresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/StashPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/suppliers/MovieDataSupplier.kt
- app/src/main/res/layout/title.xml
A big step for #21 & part of #13
Adds basic support for movies which just lists the scenes that are part of a movie. It reuses the performer view which is not great.
Searching, default filters, etc are all supported
> Add basic support for movies

- app/src/main/java/com/github/damontecres/stashapp/QueryEngine.kt
Seems it is up to the client to request a random sort seed, so `QueryEngine` now looks for a random sort and generates a random seed.
> Fixes random sort filters

- app/src/main/java/com/github/damontecres/stashapp/Constants.kt
- app/src/main/java/com/github/damontecres/stashapp/PlaybackVideoFragment.kt
- app/src/main/res/values/arrays.xml
- app/src/main/res/xml/root_preferences.xml
- build.gradle.kts
The app will always use a direct stream if possible, but if not, it will fallback on the stream selected by this new preferences. It defaults to `MP4`.
From my testing the best option can vary between devices. Maybe in the future, there will be a way to automatically select the best option.
Maybe helps with #6
> Add preference for which stream to use

- README.md
- app/src/main/res/values/dimens.xml
Increase the max lines from the default of 5 to 18. 18 seems to be the limit that fits on the screen well.
Ideally, the details would be "clickable" which would expand to the full description, but I haven't figured out how to add that yet. It would likely require implementing a custom `VideoDetailsFragment`/`DetailsSupportFragment`.
> Override video details max lines

- .github/workflows/release.yml
`r0adkll/sign-android-release` is unmaintained and failed for the `v0.0.5` release ([here](https://github.com/damontecres/StashAppAndroidTV/actions/runs/7496976245) & [here](https://github.com/damontecres/StashAppAndroidTV/actions/runs/7497082811)), so just remove it for now.
> Disable release builds

- app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/data/StashCustomFilter.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/StashFilterPresenter.kt
Fixes #35
We should not assume that the `direction` and/or `sortBy` is not-null as returned from the server. So this PR, updates the parsing for custom filters (aka premade filters).
Also enables Movies on the front page which was missed in #33.
> Fix when direction or sortBy is null from server

- app/src/main/java/com/github/damontecres/stashapp/Constants.kt
- app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/QueryEngine.kt
- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
Closes #35 
Some servers seem to return the sortBy key in a different case (sortBy vs sortby). This PR adds checking for either and also falling back on a "sane" default if not found.
Additionally, some more logging is added for better debugging in the future.
> Fixes sorting for filters & more logging

- README.md
- app/src/main/java/com/github/damontecres/stashapp/Constants.kt
- app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
Adds some logic to check for the minimum supported Stash version (`0.23.0`).
I have not thoroughly vetted every version, but `0.23.0` included https://github.com/stashapp/stash/pull/4054 and all of the filter parsing code in this app depends on that change.
> Better version checking & handling

- app/src/main/graphql/SaveSceneActivity.graphql
- app/src/main/java/com/github/damontecres/stashapp/Constants.kt
- app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/MutationEngine.kt
- app/src/main/java/com/github/damontecres/stashapp/PlaybackVideoFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/ServerPreferences.kt
- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/data/Scene.kt
Closes #32 
This PR adds a few things:
1. Loading configuration from the server and persisting it locally in `ServerPreferences`
2. Adds `MutationEngine` - similar to `QueryEngine` but for submitting mutation
3. Adds `sceneSaveActivity` graphql mutation
4. Retrieves & persists the resume time from the server
> Retrieve & persist the resume time from the server

- app/src/main/AndroidManifest.xml
- app/src/main/graphql/FindPerformers.graphql
- app/src/main/graphql/FindScenes.graphql
- app/src/main/graphql/FindTags.graphql
- app/src/main/graphql/Fragments.graphql
- app/src/main/graphql/SetTagsScene.graphql
- app/src/main/java/com/github/damontecres/stashapp/MutationEngine.kt
- app/src/main/java/com/github/damontecres/stashapp/QueryEngine.kt
- app/src/main/java/com/github/damontecres/stashapp/SearchForActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/SearchForFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/StashItemViewClickListener.kt
- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/actions/AddTagAction.kt
- app/src/main/java/com/github/damontecres/stashapp/actions/StashAction.kt
- app/src/main/java/com/github/damontecres/stashapp/data/DataType.kt
- app/src/main/java/com/github/damontecres/stashapp/data/Tag.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/ActionPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/StashPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/suppliers/TagDataSupplier.kt
Part of #3 
Adds a new row to the video details page for actions. The only action currently is to add a tag to the scene.
This PR adds a generic "Search For" activity that allows for searching any supported data type and returning the ID of the selected item.
Also refactors the Tag parsing from graphql by introducing a fragment to reduce redundant code.
> Add ability to add a new tag to a scene

- app/src/main/graphql/Configuration.graphql
- app/src/main/java/com/github/damontecres/stashapp/MutationEngine.kt
- app/src/main/java/com/github/damontecres/stashapp/ServerPreferences.kt
- app/src/main/java/com/github/damontecres/stashapp/SettingsFragment.kt
- app/src/main/res/xml/root_preferences.xml
Another addition to #3 based on a [suggestion](https://github.com/damontecres/StashAppAndroidTV/issues/3#issuecomment-1872447939)
Allows for triggering a library scan and generate task using the default settings (that the server provides).
They can be triggered in the settings menu.
> Add triggering a library scan & generate task in settings

- CONTRIBUTING.md
- app/src/main/AndroidManifest.xml
- app/src/main/graphql/FindSceneMarkers.graphql
- app/src/main/graphql/FindScenes.graphql
- app/src/main/java/com/github/damontecres/stashapp/FilterListActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/MainTitleView.kt
- app/src/main/java/com/github/damontecres/stashapp/MarkerListActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/SearchForFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/StashItemViewClickListener.kt
- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/data/DataType.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/MarkerPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/StashPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/suppliers/MarkerDataSupplier.kt
- app/src/main/java/com/github/damontecres/stashapp/util/Comparators.kt
- app/src/main/java/com/github/damontecres/stashapp/util/FilterParser.kt
- app/src/main/java/com/github/damontecres/stashapp/util/QueryEngine.kt
- app/src/main/res/layout/title.xml
Adds support for Scene Markers.
1. Browse the list of markers from main page top bar using the default filter
2. Browse the list of markers on the video details page
Clicking a marker will play the video at that marker point.
> Add support for markers

- app/src/main/java/com/github/damontecres/stashapp/StashSearchFragment.kt
Generalizes search to use any supported data type.
This will make future data types automatically supported for searching.
Follows up on #55 to search markers as well.
> Refactor search to allow any supported data type

- app/src/main/java/com/github/damontecres/stashapp/util/Constants.kt
Closes #58 
Use the path segments provided by the user and just ensure the last one is `graph` instead of replacing the path completely.
> Support proxy by URL prefix

- app/src/main/java/com/github/damontecres/stashapp/suppliers/StashPagingSource.kt
- app/src/main/java/com/github/damontecres/stashapp/util/QueryEngine.kt
Fixes a bug where clicking `View All` at the end of a list on the front page whose filter's sort by is `random` was not actually random.
Now the sort by random will be updated and send to the server.
> Fix randomization for front page filter with random sort

- README.md
- app/src/main/java/com/github/damontecres/stashapp/PlaybackExoFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/PlaybackVideoFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/StashSearchFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/actions/StashAction.kt
- app/src/main/java/com/github/damontecres/stashapp/data/DataType.kt
- app/src/main/java/com/github/damontecres/stashapp/data/Scene.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/DetailsDescriptionPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/ScenePresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/StashPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/util/Constants.kt
- app/src/main/res/values/colors.xml
1. Use a marquee on selected items when the title is too long
2. Use a unicode icon for tag & performer counts (this is easier than using an svg image)
3. Updates to the video details page
4. Only show rows if there's actual content
5. Add ability to force a scene to play via transcode
https://github.com/damontecres/StashAppAndroidTV/assets/154766448/aff09ae7-afef-4df4-9ea7-4ef8fdabeb01
> UI/UX Improvements

- app/build.gradle.kts
- app/src/main/java/com/github/damontecres/stashapp/PlaybackExoFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/data/Scene.kt
- app/src/main/java/com/github/damontecres/stashapp/util/QueryEngine.kt
- app/src/main/java/com/github/damontecres/stashapp/util/StashPreviewLoader.kt
- app/src/main/res/drawable/video_frame.xml
- app/src/main/res/layout/exoplayer_controls.xml
- app/src/main/res/layout/video_playback.xml
- app/src/main/res/values/dimens.xml
Adds showing preview thumbnails of the video when scrubbing (moving on the progress bar), if the thumbnails are available ("scrubber sprites" from a library scan or a generate task on the server).
This only works for the ExoPlayer implementation.
There's a strange issue where if the controls are visible, 2000ms go by and the progress bar moves to the bottom, then ~2000ms more the controls are hidden. During the first 2000ms, the back button will hide all of the controls, but during the second 2000ms, `videoView.isControllerFullyVisible` returns false, so the playback is stopped. For now I feel like the benefit of having previews outweighs this issue.
> Show preview thumbnails when scrubbing

- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
Just fixes a small UI bug where if a scene has no tags and/or performers and you add one, the list of tags/performers wouldn't be displayed.
This change ensure that the tags & performers list are always shown if a new item is added.
> Ensure tags/performers are shown after adding the first

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/damontecres/stashapp/StashApplication.kt
- app/src/main/java/com/github/damontecres/stashapp/util/QueryEngine.kt
Just adds some logic to store when the version of the installed app changes.
In the future, this would allow for prompting users about new features or migrating data when upgrading to a new version. For now, the data is just stored and isn't used yet.
> Store changed version

- app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/SettingsFragment.kt
- app/src/main/res/xml/root_preferences.xml
Adds a feature to configure multiple servers and switch between them. Some users reporting using multiple servers and this would also make testing easier.
The UI is a bit clunky, but works okay.
> Allow for configuring multiple servers

- app/src/main/java/com/github/damontecres/stashapp/MainActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/util/QueryEngine.kt
When returning to the main screen from a scene's page, that scene's data will be refreshed from the server. This means the playback position, tags, and performers will be updated if they changed.
Additionally, the back button navigation on the main screen is now consistent with [Android's recommendations](https://developer.android.com/training/tv/start/navigation#back_button_navigation). When back is pressed, it will return to the start of the row, then to the first row, then finally quit the app.
This PR partially resolves #73 (for the main page, but other scene lists still have this issue)
> Main screen UX enhancements

- app/build.gradle.kts
Since the `develop` tag gets moved with every merge to main, it's always the latest tag and during the `v.0.0.9` release, it was used instead of the real version.
This PR fixes that by only considering the `v+` tags.
> Ensure the tag used for version is not develop

- app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/StashGridFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/StashItemViewClickListener.kt
- app/src/main/java/com/github/damontecres/stashapp/data/StashSavedFilter.kt
- app/src/main/java/com/github/damontecres/stashapp/suppliers/StashPagingSource.kt
- app/src/main/java/com/github/damontecres/stashapp/util/QueryEngine.kt
- app/src/main/res/xml/root_preferences.xml
Updates the `View All` button at the end of rows on the main page so that if they are random, the same random sort is used on the grid view.
Additionally, after loading data on the grid, it will scroll to the "next" result. In other words, if 25 scenes are showing in a row, when clicking `View All`, the grid will scroll down to the 26th item so you can continue. This scrolling is enabled by default, but can be disabled in settings.
> Better "View All" handling for random filters & scroll to next

- app/src/main/AndroidManifest.xml
- app/src/main/graphql/SaveSceneActivity.graphql
- app/src/main/java/com/github/damontecres/stashapp/PlaybackExoFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/PlaybackVideoFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/StashItemViewClickListener.kt
- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/DetailsDescriptionPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/util/Constants.kt
- app/src/main/java/com/github/damontecres/stashapp/util/MutationEngine.kt
- app/src/main/java/com/github/damontecres/stashapp/util/ServerPreferences.kt
- app/src/main/res/layout/activity_details.xml
Closes #80 
I had thought it was just a UI glitch that scene resume times weren't updating, but turns out the new player in #62 did not implement the tracking at all.
This PR adds the tracking to the new player if tracking is enabled server side. Additionally, a rough implementation copy of the [tracking from the server](https://github.com/stashapp/stash/blob/v0.24.3/ui/v2.5/src/components/ScenePlayer/track-activity.ts) is added to increment play count, except the timer runs every 10s instead 1s. This change only applies to the new ExoPlayer, not the old default player.
Also scene details are fetched every time on the video details page instead of using the caller's data (which might be outdated). This ensures the latest resume time is available.
> Fix activity tracking for Exo Player

- app/src/main/java/com/github/damontecres/stashapp/PlaybackActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/PlaybackExoFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/PlaybackVideoFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
Fixes #86 
During playback, the device won't go into ambient mode (aka screen saver or screen off). If playback is paused, the device can go into ambient mode based on [Android's recommendations](https://developer.android.com/docs/quality-guidelines/tv-app-quality#ambient-mode).
Also fixes a minor UI bug where the play actions could be added twice.
> Keep device screen awake during playback

- .gitignore
- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/damontecres/stashapp/SettingsFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/StashApplication.kt
- app/src/main/java/com/github/damontecres/stashapp/util/Constants.kt
- app/src/main/java/com/github/damontecres/stashapp/util/UnsafeOkHttpGlideModule.kt
- app/src/main/res/xml/root_preferences.xml
Closes #2 
Adds a settings to allow trusting self-signed (technically all) certificates.
Sometimes restarting the app is required to ensure the setting is used properly since it involves modifying some static classes.
> Add option to trust self signed certs

- app/src/main/java/com/github/damontecres/stashapp/presenters/StashPresenter.kt
Fixes #93 
Set the icons for all DataTypes every time to ensure if a card doesn't have a particular icon, it will be hidden.
> Fix reuse of icons

- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/ActionPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/MarkerPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/MoviePresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/OCounterPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/PerformerPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/PopupOnLongClickListener.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/ScenePresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/StashFilterPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/StashPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/StudioPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/TagPresenter.kt
Closes #52 
Long click on a performer or tag on the scene view and select `Remove` to remove it from the scene.
This PR also refactors `StashPresenter` to be more strongly typed so there's less casting.
> Remove performers or tags from a scene

- app/src/main/graphql/SceneUpdate.graphql
- app/src/main/java/com/github/damontecres/stashapp/SearchForFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/actions/StashAction.kt
- app/src/main/java/com/github/damontecres/stashapp/util/MutationEngine.kt
Adds an action to the scene details page to create a new scene marker from the scene's current position. It only set a primary tag, no name or secondary tags.
Also a small UI follow up to #98 to remove the row if there the last item was removed.
> Add ability to create a scene marker

- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
Previously, if a scene had no markers and then you added a new one via the app, the new one wouldn't appear on the details page. This PR fixes that by ensuring the adapter row is always added to the page after creating a new marker.
> Ensure new markers appear when none existed before

- app/src/main/java/com/github/damontecres/stashapp/util/ServerPreferences.kt
Don't indiscriminately cast untyped values from the server config anymore. Instead, parse the values with some error handling.
My test server seemingly spontaneously started returning `minimumPlayPercent` as a `String` instead of an `int`, so the types returned are not necessarily reliable.
> Add some error handling when parsing server preferences

- app/src/main/java/com/github/damontecres/stashapp/SettingsFragment.kt
- app/src/main/res/xml/root_preferences.xml
Specifying the minimums for a `SeekBarPreference` in XML require API>=26, but settings it code does not, so move that configuration to code.
Also, refresh the server preferences on resume which will occurs after switching servers.
> Set some minimums in settings

- app/src/main/java/com/github/damontecres/stashapp/PlaybackExoFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/StashPlayerView.kt
- app/src/main/res/layout/video_playback.xml
- app/src/main/res/xml/root_preferences.xml
Adds a preference (enabled by default) to skip back or skip forward when pressing the D-Pad left button or right button respectively.
This only works for ExoPlayer.
> Add option to skip back/forward with D-Pad left/right on ExoPlayer

- app/src/main/graphql/SceneUpdate.graphql
- app/src/main/java/com/github/damontecres/stashapp/StashOnFocusChangeListener.kt
- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/DetailsDescriptionPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/util/MutationEngine.kt
- app/src/main/java/com/github/damontecres/stashapp/util/ServerPreferences.kt
- app/src/main/res/layout/lb_details_description.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
Adds the scene's rating to the scene details page. If the type is `start`, a `RatingBar` (five stars) is used, otherwise for `decimal` a `SeekBar` is used.
You can highlight the rating and move it left/right and then press enter/OK to set the new rating.
Like usual, the UI is a bit rough, but it's a great feature to add I think and work on refining later.
> Add rating to scene details and allow updating the rating

- app/src/main/java/com/github/damontecres/stashapp/MainTitleView.kt
- app/src/main/res/layout/title.xml
Closes #94 
Switch the `SearchOrbView` to an `ImageButton` instead.
> Fix the green circle on the search button

- app/src/main/java/com/github/damontecres/stashapp/PerformerFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/DetailsDescriptionPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/util/Constants.kt
- app/src/main/res/layout/lb_details_description.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/xml/root_preferences.xml
Adds a preference (enabled by default) which adds scrolling to scenes with long details. Long details are about ~18 lines or longer.
When enabled, the entire details section is scrollable and must be scrolled to the bottom to move to the rows below. If no scrolling is needed, then it acts as if disabled.
When disabled, the details section is truncated to whatever fits in the view.
> Add option to scroll long scene details text

- app/src/main/java/com/github/damontecres/stashapp/PlaybackExoFragment.kt
- app/src/main/res/values/arrays.xml
- app/src/main/res/xml/root_preferences.xml
Adds a new preference to control what happens when playback of a scene finished:
1. `Do nothing` - Default & current behavior where the last frame remains in view
2. `Repeat scene` - Restart playback from the beginning
3. `Return to scene details` - Close the player and return the scene details page (markers will return the previous page)
> Add preference to control behavior when playback finishes

- app/src/main/java/com/github/damontecres/stashapp/presenters/DetailsDescriptionPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/util/ServerPreferences.kt
The rating type for `stars` was being inconsistently used and this PR fixes that.
> Fixes using the right value for 'stars'

- app/src/main/java/com/github/damontecres/stashapp/SearchForFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/StashItemViewClickListener.kt
When adding a performer or tag to a scene, you can long click on the performer/tag to navigate to it's page. Then press back to return and potentially add it.
This is helpful to double-check that it's the right performer for example.
> Add a popup to go to a Performer/Tag when searching to add one to a scene

- app/src/main/java/com/github/damontecres/stashapp/presenters/StashPresenter.kt
When the cards get recycled after scrolling around, ensure the image is visible.
> Ensure card image are always shown after scrolling

- app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/util/Constants.kt
- app/src/main/java/com/github/damontecres/stashapp/util/MutationEngine.kt
- app/src/main/java/com/github/damontecres/stashapp/util/QueryEngine.kt
The networks calls should happen with `Dispatchers.IO` so that UI updates are not blocked. The UI blocking is probably not signifcant on a fast LAN connection, but just in case.
> Move network calls to IO dispatcher

- app/src/main/java/com/github/damontecres/stashapp/presenters/StashImageCardView.kt
Realized that stopping the video preview playback got lost in the shuffle.
This isn't really noticeable unless the audio is enabled, but this prevents the video/audio from playing the background after navigating off of a card.
> Stop video preview when not selected

- app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/PopupOnLongClickListener.kt
- app/src/main/res/color/popup_background_selector.xml
- app/src/main/res/layout/popup_item.xml
- app/src/main/res/values/colors.xml
Updates the default orange & black colors of the long click popup to be more in line with the app's color palette using darker variants of the card background and selected colors.
> Update popup style

- app/src/main/java/com/github/damontecres/stashapp/presenters/StashImageCardView.kt
- app/src/main/res/layout/lb_image_card_view.xml
- app/src/main/res/layout/video_playback.xml
Adds a slight fade transition between showing the image & video on a card.
Also sets the background for videos to be black which looks much better when a video doesn't match the device's aspect ratio.
> Fade between image & video on cards

- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/StashImageCardView.kt
- app/src/main/res/drawable/default_background.xml
- app/src/main/res/layout/lb_image_card_view.xml
In #81, scene details were updated to fetch during `onResume` which meant that all of the markers, performers, etc would be reset. This meant everything could flash for a second. Also meant that the selected item would revert to the beginning of the list.
So this PR moves the initial fetch of scene data to `onViewCreated` and does a refresh in `onResume` so those UI glitches won't happen.
This PR also moves some of the UI initialization to _before_ fetching the scene data and removes the temporary background image so there isn't a strange color swap.
> Fixes to scene details UI glitches

- app/src/main/java/com/github/damontecres/stashapp/FilterListActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/StashGridFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/StashItemViewClickListener.kt
- app/src/main/res/values/strings.xml
On the filter page for tags, adds a popup to go to scenes or scene markers with that tag.
A side effect of this change is that the filters are added to the back stack, so pressing back will go to the previous filtered view instead of the main screen.
> Add popup to go to the scene markers for a tag

- app/src/main/java/com/github/damontecres/stashapp/FilterListActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
The fragment found in the back stack listener may be null, so it needs to be cast that way.
Additionally, the first fragment in the activity should not be added to the back stack so that if it's visible, the activity will finish instead of just removing the fragment (and requiring another back button to finish the activity).
Follow up to #146
> Fix crash in FilterListActivity & back stack list

- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
If there is no scene cover/screenshot, trying to load the default SVG as a Bitmap would error out.
This PR (in addition to #154) can prevent a crash.
> Fix some potential scene image loading issues

- app/src/main/res/drawable/scrollbar_thumb.xml
- app/src/main/res/layout/lb_details_description.xml
- app/src/main/res/layout/performer_view.xml
Fixes #160 
`scrollbarThumbVertical` is technically a drawable, but it seems that newer devices happily accept a color to use, but some devices (such as Fire TV devices running Fire OS 6 or 7) will crash.
So this PR updates the scrollviews to use a drawable.
> Use a drawable instead of color for scrollbars to support older devices

- app/convert_strings.py
Specify explicitly to use utf-8 in the string converter script.
Some platforms may default to a different encoding which may not parse all of the translations.
> Use utf-8 encoding for python script

- app/src/main/java/com/github/damontecres/stashapp/FilterListActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/PerformerActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/StashGridFragment.kt
Fixes #150 
If the caller (`View All` button) requests to scroll to the next page and the user has the preference enabled, only scroll if it's the first filter fragment loaded. Switching to another filter will always start at the beginning now.
> Only scroll to next page on first filter load

- app/src/main/java/com/github/damontecres/stashapp/PlaybackActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/PlaybackExoFragment.kt
On some devices, button presses aren't dispatched the same way, so this PR adds `dispatchKeyEvent` to playback activity which delegates to the ExoPlayer.
I think this will fix #97.
> Fix some cases where the media controls don't appear

- app/src/main/java/com/github/damontecres/stashapp/presenters/StashImageCardView.kt
Image's don't have a background so that transparent images show the card background.
Since the entire card's background changes when selected, this means the selected color will flash for a moment when switching to the video.
Changing the background to black before switching will remove that flash since the video background is also black. And then changing it back after will use the transparency.
> Fix blue flash when card video starts on some devices

- app/src/main/java/com/github/damontecres/stashapp/ClassOnItemViewClickedListener.kt
- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/actions/CreateMarkerAction.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/CreateMarkerActionPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/StashPresenter.kt
Fixes #168 
Updates the `Create Marker` action to be its own data class so it updates correctly.
Additionally, to support this change, this PR introduces `ClassOnItemViewClickedListener` which is analogous to `ClassPresenterSelector` but for item clicks. I think, eventually, `StashItemViewClickListener` should be refactored into this new class.
> Always update the Create Marker action position

- app/src/main/java/com/github/damontecres/stashapp/PlaybackExoFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
When the "Return to scene" is enabled when a video finishes, it wasn't returning a result. Sometimes it would cause a hang on the UI thread and then crash.
> Fix a crash when a video finishes and return to scene is enabled

- app/src/main/java/com/github/damontecres/stashapp/presenters/StashPresenter.kt
If there's a lot of cards to scroll through and some do not have a video preview, the card view is reused with a previous card's video URL and the card shows a different card's video preview.
This PR ensures that the video URL is cleared before reusing the card view to prevent this.
> Ensure video previews aren't reused

- app/src/main/java/com/github/damontecres/stashapp/PlaybackExoFragment.kt
- app/src/main/res/layout/exo_player_control_view.xml
- app/src/main/res/xml/root_preferences.xml
Adds the scene title to the playback controls on ExoPlayer above the progress bar.
This can be turned off in settings.
> Add scene title to ExoPlayer

- app/src/main/java/com/github/damontecres/stashapp/presenters/PerformerPresenter.kt
- app/src/main/java/com/github/damontecres/stashapp/presenters/StudioPresenter.kt
Similar to #172, the content text for performers and studios could be reused.
This PR ensures that the content text is always set to something (or null).
> Fixes performers & studios content text being reused

- app/src/main/java/com/github/damontecres/stashapp/GalleryActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/ImageActivity.kt
- app/src/main/java/com/github/damontecres/stashapp/StashGridFragment.kt
- app/src/main/java/com/github/damontecres/stashapp/StashItemViewClickListener.kt
- app/src/main/java/com/github/damontecres/stashapp/suppliers/StashPagingSource.kt
- app/src/main/java/com/github/damontecres/stashapp/util/Constants.kt
- app/src/main/res/layout/image_layout.xml
Part of #182
When viewing a gallery's images, it's now possible to scroll/move between images with left/right on the D-Pad if the image details overlay is not showing.
For now, this is only possible when viewing the images from the gallery's page.
> Add image scrolling for galleries

- app/src/main/java/com/github/damontecres/stashapp/ui/components/prefs/ComposablePreference.kt
- app/src/main/java/com/github/damontecres/stashapp/ui/components/prefs/PreferencesContent.kt
- app/src/main/java/com/github/damontecres/stashapp/ui/components/prefs/StashPreference.kt
- app/src/main/java/com/github/damontecres/stashapp/util/AppUpgradeHandler.kt
- app/src/main/java/com/github/damontecres/stashapp/util/StashPreferencesSerializer.kt
Catch exceptions during settings migrations so one error doesn't block the whole process.
Also the default settings creation now uses the preference objects for default values.
> Catch exceptions when migrating settings

- app/src/main/java/com/github/damontecres/stashapp/ui/cards/Cards.kt
- app/src/main/java/com/github/damontecres/stashapp/ui/components/Rating.kt
Fixes being unable to set the rating to 1 (or half) star
Also the rating is no longer shown on cards if it is zero (or null/unset)
> Fix setting rating to 1 star
