.github/workflows/pr.yml
app/src/main/AndroidManifest.xml
app/src/main/java/com/github/damontecres/stashapp/ErrorFragment.kt
app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
app/src/main/java/com/github/damontecres/stashapp/PerformerFragment.kt
app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt

Just adding a workflow for PRs which builds the app to ensure everything compiles

Add basic GHA workflow to build the app for PRs

---

app/build.gradle.kts

Calculate the `versionCode` from the list of tags.
This does two things:
1. Every new tag will automatically increase the `versionCode`
2. No commit is required to increment the `versionCode`, so a release can be created from any commit

Calculate versionCode

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
app/src/main/java/com/github/damontecres/stashapp/MainTitleView.kt
app/src/main/java/com/github/damontecres/stashapp/StashGridFragment.kt
app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/ScenePresenter.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_tag.xml
app/src/main/res/layout/title.xml
app/src/main/res/values-night/styles.xml
app/src/main/res/values/styles.xml
app/src/main/res/values/themes.xml

A lot of UI improvements (in my opinion at least)!
1. Use colors from default Stash CSS style
2. Only show the title bar on the main activity
3. Add resolution & duration to scene images
4. Better margins on several screens
Closes #14 (maybe?)
<details><summary>Click for sample images of new UI</summary>
<p>
</p>
</details>

Lots of UI improvements

---

.github/workflows/main.yml

Add publishing a debug build to a pre-release on merges to `main`

Add develop build workflow

---

.github/workflows/main.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.gitignore
app/build.gradle.kts

Develop & release builds will now be signed automatically

Add automatic signing to CI builds

---

app/src/main/java/com/github/damontecres/stashapp/PlaybackExoFragment.kt
app/src/main/res/layout/exo_player_control_view.xml
app/src/main/res/layout/video_playback.xml
app/src/main/res/xml/root_preferences.xml

Follow up from #65 to fix hiding controls correctly and better back button handling.
Also allows customizing the controller auto hide time or set to 0 to always show controls.

Fixes to playback controls

---

app/src/main/java/com/github/damontecres/stashapp/presenters/ScenePresenter.kt

Adds a small bar presenter how much of a scene has been watched to the scene image.

Add watched percent bar to scene presenter

---

README.md
app/src/main/java/com/github/damontecres/stashapp/PerformerActivity.kt
app/src/main/java/com/github/damontecres/stashapp/PerformerFragment.kt
app/src/main/java/com/github/damontecres/stashapp/StashGridFragment.kt
app/src/main/res/layout/performer_view.xml

UI updates to the performer view to include many more details!

Performer view overhaul

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/github/damontecres/stashapp/DebugActivity.kt
app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
app/src/main/java/com/github/damontecres/stashapp/SettingsFragment.kt
app/src/main/java/com/github/damontecres/stashapp/util/ServerPreferences.kt
app/src/main/res/layout/debug.xml
app/src/main/res/layout/frame_layout.xml

Just adds an activity to display some debugging information.
Click the version in settings a few times to bring it up.

Add a debug activity

---

app/src/main/graphql/SaveSceneActivity.graphql
app/src/main/java/com/github/damontecres/stashapp/StashItemViewClickListener.kt
app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
app/src/main/java/com/github/damontecres/stashapp/actions/StashActionClickedListener.kt
app/src/main/java/com/github/damontecres/stashapp/data/OCounter.kt
app/src/main/java/com/github/damontecres/stashapp/data/Scene.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/OCounterPresenter.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/StashPresenter.kt
app/src/main/java/com/github/damontecres/stashapp/util/MutationEngine.kt
app/src/main/res/drawable/sweat_drops.xml

Add action to increment the O-Counter for a scene

---

app/src/main/java/com/github/damontecres/stashapp/data/Scene.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/DetailsDescriptionPresenter.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/ScenePresenter.kt
app/src/main/java/com/github/damontecres/stashapp/util/Constants.kt

Always fallback to filename if a scene has no title

---

app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt

Closes #101
Follow up to #100 to fix creating the first scene marker on a scene and also ensuring the markers are sorted when adding/removing.

Follow up bug fixes to #100

---

app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
app/src/main/java/com/github/damontecres/stashapp/MainTitleView.kt
app/src/main/java/com/github/damontecres/stashapp/PlaybackExoFragment.kt
app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
app/src/main/java/com/github/damontecres/stashapp/actions/StashAction.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/StashFilterPresenter.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/StashPresenter.kt
app/src/main/java/com/github/damontecres/stashapp/util/Constants.kt
app/src/main/java/com/github/damontecres/stashapp/util/UnsafeOkHttpGlideModule.kt
app/src/main/res/layout/video_playback.xml

Closes #99 
Closes #94
Maybe #97 will be fixed, but at least adds some extra logging to help diagnose.
Also fixes a few UI issues and ignored exceptions that clutter the logs.

Minor UI & bug fixes

---

app/src/main/graphql/SaveSceneActivity.graphql
app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
app/src/main/java/com/github/damontecres/stashapp/util/MutationEngine.kt

You can decrement or reset the O-Counter with a long press

Ensure Create Marker card is always updated & add decrement/reset to O-Counter

---

app/src/main/java/com/github/damontecres/stashapp/PlaybackExoFragment.kt

Adds a listener for the controls to hide them better

Hide the scrubber bar when center controls are not visible

---

app/src/main/res/layout/exo_player_control_view.xml

Add the settings button to the ExoPlayer controls.
This button will present options to control the playback speed.

Add settings to Exo playback controls to control play speed

---

app/src/main/java/com/github/damontecres/stashapp/PlaybackExoFragment.kt
app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/OCounterPresenter.kt
app/src/main/res/layout/exo_player_control_view.xml

Closes #102 
Adds a button & count to the playback controls and update logic so that the playback & details pages stay in sync.

Add O-Counter button to playback control row

---

app/src/main/java/com/github/damontecres/stashapp/FilterListActivity.kt
app/src/main/java/com/github/damontecres/stashapp/StashGridFragment.kt
app/src/main/res/values/strings.xml

Adds a long-click popup to Markers to navigate to the scene details for that marker.

Add long click to scene markers to go to the scene

---

app/build.gradle.kts
app/src/main/java/com/github/damontecres/stashapp/MovieFragment.kt
app/src/main/java/com/github/damontecres/stashapp/PerformerFragment.kt
app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/MarkerPresenter.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/MoviePresenter.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/PerformerPresenter.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/ScenePresenter.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/StashPresenter.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/StudioPresenter.kt
app/src/main/java/com/github/damontecres/stashapp/util/StashGlideModule.kt
app/src/main/java/com/github/damontecres/stashapp/util/svg/SvgDecoder.kt
app/src/main/java/com/github/damontecres/stashapp/util/svg/SvgDrawableTranscoder.kt
app/src/main/java/com/github/damontecres/stashapp/util/svg/SvgSoftwareLayerSetter.kt

Closes #16 
Adds a fallback to parse SVGs from the server

Add fallback to loading svg default images

---

app/src/main/graphql/Configuration.graphql
app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
app/src/main/java/com/github/damontecres/stashapp/MainTitleView.kt
app/src/main/java/com/github/damontecres/stashapp/util/ServerPreferences.kt

Closes #56 
Use the server provided config for which menu items to display at the top of the main page.

Only show the top buttons that the server has configured

---

app/src/main/java/com/github/damontecres/stashapp/MovieFragment.kt
app/src/main/java/com/github/damontecres/stashapp/PlaybackExoFragment.kt
app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
app/src/main/java/com/github/damontecres/stashapp/util/ServerPreferences.kt
app/src/main/java/com/github/damontecres/stashapp/util/StashCoroutineExceptionHandler.kt
app/src/main/res/values/strings.xml

Adds an optional `Toast` to `StashCoroutineExceptionHandler` to give feedback when an error occurs.

Update coroutine error handling

---

app/src/main/java/com/github/damontecres/stashapp/FilterListActivity.kt
app/src/main/java/com/github/damontecres/stashapp/SearchForFragment.kt
app/src/main/java/com/github/damontecres/stashapp/StashItemViewClickListener.kt
app/src/main/java/com/github/damontecres/stashapp/StashSearchFragment.kt
app/src/main/java/com/github/damontecres/stashapp/data/StashCustomFilter.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/StashFilterPresenter.kt

Makes two improvements when searching:
1. Add a 'View All' button to the end of each data type row when searching similar to the main page
- This displays all of the results for the query & data type
2. Adds "suggestions" when adding a Tag or Performer to a scene
- The "suggestions" are really just the tags/performers with the highest scene count

Search improvements

---

app/src/main/graphql/FindScenes.graphql
app/src/main/java/com/github/damontecres/stashapp/PlaybackExoFragment.kt
app/src/main/java/com/github/damontecres/stashapp/StashApplication.kt
app/src/main/java/com/github/damontecres/stashapp/StashExoPlayer.kt
app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/ScenePresenter.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/StashImageCardView.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/StashPresenter.kt
app/src/main/res/xml/root_preferences.xml

A follow up to #125 to fix some UI bugs.
Also adds an option to disable audio when previews are playing.

A few bug fixes to the video previews

---

app/src/main/java/com/github/damontecres/stashapp/FilterListActivity.kt
app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
app/src/main/java/com/github/damontecres/stashapp/PerformerActivity.kt
app/src/main/java/com/github/damontecres/stashapp/SettingsFragment.kt
app/src/main/java/com/github/damontecres/stashapp/StashGridFragment.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/StashImageCardView.kt
app/src/main/java/com/github/damontecres/stashapp/util/Constants.kt
app/src/main/res/values/arrays.xml
app/src/main/res/xml/root_preferences.xml

Add a preference to set the size of cards. This replaces the number of columns preference.

Customize card sizes

---

app/src/main/java/com/github/damontecres/stashapp/util/Constants.kt
app/src/main/java/com/github/damontecres/stashapp/util/MutationEngine.kt
app/src/main/java/com/github/damontecres/stashapp/util/QueryEngine.kt

Closes #137
Reduces the work done on the IO thread to only the actual network calls.

Fix trying to update UI on IO thread

---

app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt

Replaces #139 
After https://github.com/damontecres/StashAppAndroidTV/pull/131 & https://github.com/damontecres/StashAppAndroidTV/pull/133, the rows on the main page load asynchronously. And the first one to load grabs the focus of the page which is not ideal.
This PR refactors so that all of the data is fetch asynchronously, but added to the UI in order.
Additionally, in the event of failures, focus will be moved to the top bar. Before focus would be lost and you have to press up to get to the bar to scroll over the settings.

Load main page content in order asychronously

---

app/src/main/java/com/github/damontecres/stashapp/FilterListActivity.kt
app/src/main/res/layout/popup_item.xml

Updates the popup for selecting a filter to match the style in #136
Also since the width is hardcoded, adds a marquee if needed to the filter names.

Update filter button popup style to match #136

---

app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
app/src/main/java/com/github/damontecres/stashapp/util/Constants.kt

Don't display empty filters on the main page

---

app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
app/src/main/java/com/github/damontecres/stashapp/SearchForFragment.kt
app/src/main/java/com/github/damontecres/stashapp/SettingsFragment.kt
app/src/main/java/com/github/damontecres/stashapp/StashGridFragment.kt
app/src/main/java/com/github/damontecres/stashapp/StashSearchFragment.kt
app/src/main/java/com/github/damontecres/stashapp/util/StashCoroutineExceptionHandler.kt

1. Ensure every coroutine launch has an exception handler

Add more error handling

---

app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
app/src/main/java/com/github/damontecres/stashapp/util/FilterParser.kt
app/src/main/java/com/github/damontecres/stashapp/util/ServerPreferences.kt
app/src/test/java/com/github/damontecres/stashapp/ObjectFilterParsingTests.kt

Updates the saved filter parsing code to make fewer assumptions and use case insensitive lookups.
Additionally, some of the error handling is updated.
Also, the server preferences are updated to use more case insensitive lookups.

Fixes a few saved filter parsing errors

---

app/src/main/res/color/focus_color.xml
app/src/main/res/color/popup_background_selector.xml
app/src/main/res/drawable/popup_item_background.xml
app/src/main/res/layout/popup_item.xml

Similar to #161, background requires a drawable, so switch the color selector to use a drawable selector.

Fix popup background to use a drawable

---

app/src/main/graphql/FindMovies.graphql
app/src/main/graphql/FindScenes.graphql
app/src/main/java/com/github/damontecres/stashapp/MovieActivity.kt
app/src/main/java/com/github/damontecres/stashapp/MovieFragment.kt
app/src/main/java/com/github/damontecres/stashapp/PerformerFragment.kt
app/src/main/java/com/github/damontecres/stashapp/VideoDetailsFragment.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/MoviePresenter.kt
app/src/main/java/com/github/damontecres/stashapp/util/QueryEngine.kt
app/src/main/res/layout/activity_movie.xml
app/src/main/res/layout/movie_view.xml

Fixes #152 
1. Updates the movie page to fix the image and include details.
2. Movie card images are scaled better (to width w/ aspect ratio retained)
3. Adds movies to scene details pages
4. Sneaks in a fix to the performer view where some text could be cut off

Updates & fixes to the movie page

---

app/src/main/java/com/github/damontecres/stashapp/MovieActivity.kt

Just fixes a build error that occurred from after a few merges

Fix build error from merge

---

.pre-commit-config.yaml
app/src/main/java/com/github/damontecres/stashapp/ClassOnItemViewClickedListener.kt
app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
app/src/main/java/com/github/damontecres/stashapp/PlaybackExoFragment.kt
app/src/main/java/com/github/damontecres/stashapp/StashExoPlayer.kt
app/src/main/java/com/github/damontecres/stashapp/StashPlayerView.kt
app/src/main/java/com/github/damontecres/stashapp/presenters/CreateMarkerActionPresenter.kt

Update the ktlint version to match Android Studio's plugin and reformat the code.

[DEV] Update ktlint version

---

app/src/main/java/com/github/damontecres/stashapp/FilterListActivity.kt
app/src/main/java/com/github/damontecres/stashapp/GalleryActivity.kt
app/src/main/java/com/github/damontecres/stashapp/ImageActivity.kt
app/src/main/java/com/github/damontecres/stashapp/MainFragment.kt
app/src/main/java/com/github/damontecres/stashapp/StashItemViewClickListener.kt
app/src/main/java/com/github/damontecres/stashapp/data/FilterType.kt
app/src/main/java/com/github/damontecres/stashapp/data/StashCustomFilter.kt
app/src/main/java/com/github/damontecres/stashapp/data/StashSavedFilter.kt
app/src/main/java/com/github/damontecres/stashapp/itemclick/ImageGridClickedListener.kt
app/src/main/java/com/github/damontecres/stashapp/itemclick/OnImageFilterClickedListener.kt
app/src/main/java/com/github/damontecres/stashapp/util/Constants.kt
app/src/main/java/com/github/damontecres/stashapp/util/QueryEngine.kt

Closes #182 
Adds scrolling/moving between images from any filter including the main page and saved filters.

Move between images from any filter

---

app/src/main/java/com/github/damontecres/stashapp/ui/PreviewUtils.kt
app/src/main/java/com/github/damontecres/stashapp/ui/components/filter/CreateFilter.kt
app/src/main/java/com/github/damontecres/stashapp/ui/components/filter/CreateObjectFilter.kt
app/src/main/java/com/github/damontecres/stashapp/ui/components/playback/PlaybackOverlay.kt
app/src/main/java/com/github/damontecres/stashapp/ui/components/prefs/PreferencesContent.kt
app/src/main/java/com/github/damontecres/stashapp/ui/components/server/InitialSetup.kt
app/src/main/java/com/github/damontecres/stashapp/ui/nav/DestinationContent.kt
app/src/main/java/com/github/damontecres/stashapp/ui/pages/SettingsPage.kt

Fixes a possible crash while switching between between filter options. I think it likely only occurs on slower devices.
Also some dev preview changes

Fix crash during create filter & some dev changes

---

app/src/main/java/com/github/damontecres/stashapp/RootActivity.kt
app/src/main/java/com/github/damontecres/stashapp/StashExoPlayer.kt
app/src/main/java/com/github/damontecres/stashapp/ui/components/StashGrid.kt
app/src/main/java/com/github/damontecres/stashapp/ui/components/prefs/StashPreference.kt
app/src/main/java/com/github/damontecres/stashapp/ui/components/server/AddServerContent.kt
app/src/main/java/com/github/damontecres/stashapp/ui/pages/PlaybackPage.kt
app/src/main/java/com/github/damontecres/stashapp/util/LoggingCoroutineExceptionHandler.kt

Fixes a few places where old settings were still used
